import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import { env } from "../config/env.js";

export function generatePrescriptionPdf(prescription) {
  const uploadDir = path.resolve("uploads", "prescriptions");
  fs.mkdirSync(uploadDir, { recursive: true });
  const fileName = `prescription-${prescription._id}.pdf`;
  const filePath = path.join(uploadDir, fileName);

  const doc = new PDFDocument({ margin: 48 });
  doc.pipe(fs.createWriteStream(filePath));

  doc.fontSize(22).text("ClinicFlow AI Prescription", { align: "center" });
  doc.moveDown();
  doc.fontSize(12).text(`Date: ${new Date(prescription.createdAt).toLocaleDateString()}`);
  doc.text(`Patient: ${prescription.patient.name}`);
  doc.text(`Doctor: ${prescription.doctor.name} (${prescription.doctor.specialization})`);
  doc.moveDown();
  doc.fontSize(14).text("Diagnosis", { underline: true });
  doc.fontSize(12).text(prescription.diagnosis);
  doc.moveDown();
  doc.fontSize(14).text("Medicines", { underline: true });
  prescription.medicines.forEach((medicine, index) => {
    doc.fontSize(12).text(`${index + 1}. ${medicine.name} - ${medicine.dosage || ""} ${medicine.frequency || ""} ${medicine.duration || ""}`);
    if (medicine.instructions) doc.text(`   ${medicine.instructions}`);
  });
  if (prescription.notes) {
    doc.moveDown();
    doc.fontSize(14).text("Notes", { underline: true });
    doc.fontSize(12).text(prescription.notes);
  }
  doc.moveDown();
  doc.fontSize(10).text("Generated by ClinicFlow AI. Follow your doctor's instructions and seek urgent care for emergencies.");
  doc.end();

  return {
    filePath,
    publicPath: `${env.baseUrl}/uploads/prescriptions/${fileName}`
  };
}
